function [Model,log10PriorMean,log10PriorStd] = dusp1ModelLibrary_Final(modelName, ...
    regenerate,modelLibrary,dataFileGR,dataFileDusp1)
arguments
    modelName
    regenerate = false
    modelLibrary = 'savedParameters/GRDusp1ModelLibrary'
    dataFileGR = 'Data/GR_SSITcellresults_Final_Sep18.csv';
    dataFileDusp1 = 'Data/DUSP1_SSITcellresults_Final_Sep18.csv';
end

if regenerate
    %% Create Base Model
    ModelBase = SSIT;
    ModelBase.species = {
        'offGene';
        'onGene' ;
        'cytGR'  ;
        'nucGR'  ;
        'rna'    ;
        'rCyt'   };
    
    ModelBase.initialCondition = [2;0;24;1;5;0];

    ModelBase.propensityFunctions = {
        '(kon_0+kon_1*nucGR)*offGene';
        'koff/(1+mkoff*nucGR)*onGene';
        '(kcn0 + (t>tau_elong)*kcn1*IDex/(MDex+IDex)) * cytGR';
        'knc*nucGR';
        'kg1';
        'gg1*cytGR';
        'gg2*nucGR';
        '(kr_off+(kr_on_0+kr_on_1*nucGR)*onGene)*Itrpt';
        'knuc2cyt*rna';
        'degCyt0*rCyt + (degCyt1-degCyt0)*1/2*(ITTP+rCyt+kDTTP - sqrt((ITTP+rCyt+kDTTP)^2 - 4*rCyt*ITTP))'};
    
    ModelBase.stoichiometry = [
     -1    1     0     0     0     0     0     0     0     0;
     1    -1     0     0     0     0     0     0     0     0;
     0     0    -1     1     1    -1     0     0     0     0;
     0     0     1    -1     0     0    -1     0     0     0;
     0     0     0     0     0     0     0     1    -1     0;
     0     0     0     0     0     0     0     0     1    -1];

    ModelBase.parameters = {...
        'koff'        ,1.6523e+02;...
        'kon_0'       ,8.9185e-03;...
        'kr_on_0'     ,2.2391e+03;...
        'knuc2cyt'    ,6.3088e-02;...
        'kcn0'        ,6.0409e-03;...
        'kcn1'        ,1.1497e-01;...
        'gDex'        ,1.0933e-06;...
        'knc'         ,1.8733e-02;...
        'kg1'         ,4.6782e-02;...
        'gg1'         ,1.1886e-03;...
        'gg2'         ,4.3274e-03;...
        'MDex'        ,1.1904e+01;...
        'Dex0'        ,       100;...
        'degCyt0'     ,2.1900e-03;...
        'degCyt1'     ,3.7242e+00;...
        'kDTTP'       ,9.8762e+01;...
        'tptlTime'    ,       200;...
        'ktptl'       ,1.0170e-01;...
        'tau_elong'   ,2.2116e+00;...
        'TTP1'        ,8.7541e-01;...
        'tTTP'        ,7.0350e+01;...
        'eta'         ,1.0237e+02;...
        'kr_off'      ,         0;...
        'kon_1'       ,6.3816e-03;...
        'mkoff'       ,1.0226e-07;...
        'kr_on_1'     ,3.2121e-06;...
        'kon_1_TTP'   ,4.0000e-03;...
        'koff_TTP'    ,         1;...
        'kr_on_TTP'   ,        10;...
        'knuc2cyt_TTP',1.0000e-02;...
        'ktranslate'  ,         1;...
        'degProt'     ,1.0000e-02;...
        'kbind'       ,         1;...
        'TTP_eta'     ,         1;...
        'unbind'      ,         1;...
        'degCyt0_TTP' ,1.0000e-02};
    % Priors (based on magnitude of previously guessed values).
    log10PriorMean = [
        0, ...'koff',0.928272906611829;
        -3, ...'kon',0.00435679746751789;
        1, ...'kr',13.6899693803118;
        -2, ...'knuc2cyt',0.0303917515033354;
        -2, ...'kcn0',0.00605936338887321;
        -1, ...'kcn1',0.100801493996861;
        -5, ...'gDex',3.06931711147851e-05;
        -2, ...'knc',0.0101878879366104;
        -1, ...'kg1',0.109965006106303;
        -3, ...'gg1',0.0035378622695277;
        -2, ...'gg2',0.00955287461619338;
        1, ...'MDex',14.1807103753798;
        NaN, ...'Dex0',100;
        -2, ...'degCyt0',0.00834750349323117;
        -2, ... %'degCyt1',0.00927999553405981
        -2, ... %'degCytA'
        NaN, ... % TPL Time (experimentally chosen)
        -1, ... % k_tptl, 0.065
        0, ...% tau_elong, 2.6024  
        -1, ... %TTP1
        2, ...  % tTTP
        1, ...   %eta
        -5, ... %kr_off
        -5, ... %kon_1
        -5, ... %mkoff
        -5, ... %kr_on_1
        -3, ... % 'kon_1_TTP'   ,4e-3;
        0 ,...  % 'koff_TTP'    ,1;
        1, ...  % 'kr_on_TTP'   ,10;
        -2, ... % 'knuc2cyt_TTP',.01;
        0, ...  % 'ktranslate'  ,1;
        -2, ... % 'degProt'     ,0.01;
        0, ...  % 'kbind'       ,1;
        0, ...  % 'TTP_eta'     ,1;
        0, ...  % 'unbind'      ,1;
        -2]';    % 'degCyt0_TTP' ,0.01}
    log10PriorStd = 2*ones(size(log10PriorMean));

    ModelBase.fspOptions.initApproxSS = true;

    ModelBase.inputExpressions = {'IDex','Dex0*exp(-gDex*(t-tau_elong))';...
        'ITTP','1+TTP1*(t^eta/(t^eta+tTTP^eta))*(t>0)';...
        'Itrpt','(t<=(tau_elong+tptlTime)) + (t>(tau_elong+tptlTime))*exp(-ktptl*(t-(tau_elong+tptlTime)))'};

    ModelBase.sensOptions.solutionMethod = 'finiteDifference';

    if exist([modelLibrary,'.mat'],"file")
        save(modelLibrary,"ModelBase",'log10PriorMean','log10PriorStd','-append');
    else
        save(modelLibrary,"ModelBase",'log10PriorMean','log10PriorStd');
    end


    %% Simplify to GR model
    ModelGR = ModelBase;
    ModelGR.parameters{19,2} = 0; % set tau_elong to zero for GR analysis.
    GRspeciesInds = [3,4];
    GRreactionInds = (3:7);
    GRparameterInds = (5:12);
    ModelGR.species = ModelGR.species(GRspeciesInds);
    ModelGR.initialCondition = ModelGR.initialCondition(GRspeciesInds);
    ModelGR.propensityFunctions = ModelGR.propensityFunctions(GRreactionInds);
    ModelGR.stoichiometry = ModelGR.stoichiometry(GRspeciesInds,GRreactionInds);
    ModelGR.fittingOptions.modelVarsToFit = (5:12);
    ModelGR.customConstraintFuns = {'cytGR+nucGR'};
    ModelGR = ModelGR.formPropensitiesGeneral('ModelGR');
    ModelGR.fspOptions.bounds = [0;0;30;30;30];
    [~,~,ModelGR] = ModelGR.solve;
    [~,~,ModelGR] = ModelGR.solve;

    %% Add GR Data and create multimodel
    GRfitCases = {'1','1',101,'GR Fit (1nM Dex)';...
        '10','10',102,'GR Fit (10nM Dex)';...
        '100','100',103,'GR Fit (100nM Dex)'};
    ModelGRparameterMap = cell(1,size(GRfitCases,1));
    ModelGRfit = cell(1,size(GRfitCases,1));
    boundGuesses = cell(1,size(GRfitCases,1));
    for i=1:3
        if i==3 % Include zero time data within the 100nM dataset. Exclude times (20,40,60,90,150) due to missing replicas.
            ModelGRfit{i} = ModelGR.loadData(dataFileGR,...
                {'cytGR','normGRcyt';'nucGR','normGRnuc'},...
                {[],[], ...
                ['(TAB.dex_conc==',GRfitCases{i,1},'|(TAB.dex_conc==0&TAB.time==0&TAB.imageDates~=20230522))&TAB.time~=20&TAB.time~=40&TAB.time~=60&TAB.time~=90&TAB.time~=150']});
        else % Exclude zero time data within the other datasets to avoid double counting in fitting. 
             % Exclude times (20,40,60,90,150) due to missing replicas.
            ModelGRfit{i} = ModelGR.loadData(dataFileGR,...
                {'cytGR','normGRcyt';'nucGR','normGRnuc'},...
                {[],[], ...
                ['TAB.dex_conc==',GRfitCases{i,1},'&TAB.time~=20&TAB.time~=40&TAB.time~=60&TAB.time~=90&TAB.time~=150']});
        end

        ModelGRfit{i}.parameters(13,:) = {'Dex0', str2num(GRfitCases{i,1})};
        ModelGRfit{i}.tSpan = ModelGRfit{i}.dataSet.times;
        ModelGRparameterMap(i) = {(1:8)};
        boundGuesses{i} = [0;0;30;30;30];
    end

    logPriorGR = @(x)-sum((log10(reshape(x,[numel(x),1]))-log10PriorMean(GRparameterInds)).^2./(2*log10PriorStd(GRparameterInds).^2));
    combinedGRModel = SSITMultiModel(ModelGRfit,ModelGRparameterMap,logPriorGR);
    combinedGRModel = combinedGRModel.initializeStateSpaces(boundGuesses);
    save(modelLibrary,"combinedGRModel",'-append');

    %% Alternative GR model with NO NUCLEAR DEGRADATION.
    combinedGRModel_CytDegOnly = combinedGRModel;
    for i = 1:3
        combinedGRModel_CytDegOnly.SSITModels{i}.parameters{11,2} = 0;
        combinedGRModel_CytDegOnly.SSITModels{i}.fittingOptions.modelVarsToFit = [5:10,12];
    end
    combinedGRModel_CytDegOnly.parameterIndices = {[1:7],[1:7],[1:7]};
    combinedGRModel_CytDegOnly.parameters = combinedGRModel_CytDegOnly.parameters([1:6,8]);
    GRparameterInds = [5:10,12];
    combinedGRModel_CytDegOnly.parameterConstraints = ...
        @(x)-sum((log10(reshape(x,[numel(x),1]))-log10PriorMean(GRparameterInds)).^2./(2*log10PriorStd(GRparameterInds).^2));
    save(modelLibrary,"combinedGRModel_CytDegOnly",'-append');

    %% Alternative GR model with NO CYTOPLASMIC DEGRADATION.
    combinedGRModel_NucDegOnly = combinedGRModel;
    for i = 1:3
        combinedGRModel_NucDegOnly.SSITModels{i}.parameters{10,2} = 0;
        combinedGRModel_NucDegOnly.SSITModels{i}.fittingOptions.modelVarsToFit = [5:9,11:12];
    end
    combinedGRModel_NucDegOnly.parameterIndices = {[1:7],[1:7],[1:7]};
    combinedGRModel_NucDegOnly.parameters = combinedGRModel_NucDegOnly.parameters([1:5,7,8]);
    GRparameterInds = [5:9,11,12];
    combinedGRModel_NucDegOnly.parameterConstraints = ...
        @(x)-sum((log10(reshape(x,[numel(x),1]))-log10PriorMean(GRparameterInds)).^2./(2*log10PriorStd(GRparameterInds).^2));
    save(modelLibrary,"combinedGRModel_NucDegOnly",'-append');

    %% Alternative GR model where Dex INHIBITS NUCLEAR EXPORT.
    combinedGRModel_DexExport = combinedGRModel;
    for i = 1:3
        combinedGRModel_DexExport.SSITModels{i}.propensityFunctions{1} = 'kcn0*cytGR';
        combinedGRModel_DexExport.SSITModels{i}.propensityFunctions{2} = 'max(0,(knuc2cyt - (t>tau_elong)*knc1*IDex/(MDex+IDex))) * nucGR';
        combinedGRModel_DexExport.SSITModels{i}.parameters(6,:) = {'knc1',0.03};
        if i == 1
            combinedGRModel_DexExport.SSITModels{i} = combinedGRModel_DexExport.SSITModels{i}.formPropensitiesGeneral('GR_Alt_Model_DexNuc2Cyt');
        else
            combinedGRModel_DexExport.SSITModels{i}.propensitiesGeneral = combinedGRModel_DexExport.SSITModels{1}.propensitiesGeneral;
        end
    end
    save(modelLibrary,"combinedGRModel_DexExport",'-append')

    %%  **********************************************************
    %%       ALT DUSP1 MODELS
    %%  **********************************************************

    %% Create General 2-State Model
    ModelDUSP1 = ModelBase;
    DUSP1speciesInds = (1:5);
    DUSP1reactionInds = (1:9);
    ModelDUSP1.species = ModelDUSP1.species(DUSP1speciesInds);
    ModelDUSP1.initialCondition = ModelDUSP1.initialCondition(DUSP1speciesInds);
    ModelDUSP1.propensityFunctions = ModelDUSP1.propensityFunctions(DUSP1reactionInds);
    ModelDUSP1.stoichiometry = ModelDUSP1.stoichiometry(DUSP1speciesInds,DUSP1reactionInds);
    ModelDUSP1.fittingOptions.modelVarsToFit = [1:4,19,23,24,25,26];  
    % All tuneable parameters that affect nuclear and TS data (excluding GR and cyto)
    ModelDUSP1.useHybrid = true;
    ModelDUSP1.hybridOptions.upstreamODEs = {'cytGR','nucGR'};
    ModelDUSP1 = ModelDUSP1.formPropensitiesGeneral('ModelDUSP1');
    ModelDUSP1.fspOptions.bounds = [0;0;0;2;2;500];
    ModelDUSP1.fittingOptions.logPrior = ...
        @(x)-sum((log10(reshape(x,[numel(x),1]))-...
        log10PriorMean(ModelDUSP1.fittingOptions.modelVarsToFit)).^2./...
        (2*log10PriorStd(ModelDUSP1.fittingOptions.modelVarsToFit).^2));
    [~,~,ModelDUSP1] = ModelDUSP1.solve;
    save(modelLibrary,"ModelDUSP1",'-append')

    %% Add 100nM Nuclear Data
    ModelDUSP1_100nM = ModelDUSP1.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'},...
        {[],[],['(TAB.dex_conc==100|(TAB.dex_conc==0&TAB.time==0))', ...
        '&TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685&isnan(TAB.time_tpl)']},{'replica'});
    ModelDUSP1_100nM.parameters{13,2} = 100;
    save(modelLibrary,"ModelDUSP1_100nM",'-append')

    %% TODO - Add three state model?
    % % if strcmpi(modelName,'GeneralThreeStateModel')||strcmp(modelName,'all')
    % GeneralThreeStateModel = ModelDUSP1_100nM;
    % GeneralThreeStateModel = GeneralThreeStateModel.addSpecies('onGene2',0);
    % GeneralThreeStateModel.parameters(23,:) = {'kr_off',0.1};
    % GeneralThreeStateModel.parameters(24,:) = {'mkoff',1e-2};
    % GeneralThreeStateModel.propensityFunctions{2} = 'koff/(1+mkoff*nucGR)*onGene';
    % GeneralThreeStateModel.parameters(25,:) = {'kon_0',0.1};
    % GeneralThreeStateModel.propensityFunctions{1} = '(kon_0+kon_1*nucGR)*offGene';
    % GeneralThreeStateModel = GeneralThreeStateModel.addReaction(struct(...
    %     'propensity','k23*onGene',...
    %     'stoichiometry',{{'onGene',-1;'onGene2',1}},...
    %     'parameters',{{'k23',5}}));
    % GeneralThreeStateModel = GeneralThreeStateModel.addReaction(struct(...
    %     'propensity','k32*onGene2',...
    %     'stoichiometry',{{'onGene2',-1;'onGene',1}},...
    %     'parameters',{{'k32',5}}));
    % GeneralThreeStateModel.propensityFunctions{8} = '(kr_off*offGene+kr_on_0*onGene+kr_1*onGene2)*Itrpt';
    % GeneralThreeStateModel.parameters(28,:) = {'kr_1',10};
    % 
    % GeneralThreeStateModel = GeneralThreeStateModel.formPropensitiesGeneral('GeneralThreeStateModel');
    % % 
    % log10PriorMean([23,24,25]) = -3;
    % log10PriorMean(26:27) = 0;
    % log10PriorStd(26:27) = 2;
    % log10PriorMean(28) = 1;
    % log10PriorStd(28) = 2;
    % 
    % GeneralThreeStateModel.fittingOptions.modelVarsToFit = [1:4,19,23:28];
    % GeneralThreeStateModel.fittingOptions.logPrior = ...
    %     @(x)-sum((log10(reshape(x,[numel(x),1]))-...
    %     log10PriorMean(GeneralThreeStateModel.fittingOptions.modelVarsToFit)).^2./...
    %     (2*log10PriorStd(GeneralThreeStateModel.fittingOptions.modelVarsToFit).^2));
    % 
    % save(modelLibrary,"GeneralThreeStateModel","log10PriorMean","log10PriorStd",'-append')
    % end
    
    %% Full ODE Model
    fullODEModel = ModelBase;
    fullODEModel.solutionScheme = 'ode';
    fullODEModel = fullODEModel.formPropensitiesGeneral('Full_GR_DUSP1_Model');

    fullODEModel_100 = fullODEModel.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['(TAB.dex_conc==100|(TAB.dex_conc==0&TAB.time==0))', ...
        '&TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685&isnan(TAB.time_tpl)']},{'replica'});
    fullODEModel_100.parameters(13,:) = {'Dex0',100};    %% Alt SSA Model With GR -| KOFF
    soln100 = fullODEModel_100.solve;
    save(modelLibrary,"fullODEModel_100",'-append')

    %% Full SSA Model
    fullSSAModel = fullODEModel_100;
    fullSSAModel.solutionScheme = 'SSA';
    fullSSAModel.tSpan = [-500,fullSSAModel.tSpan];
    fullSSAModel.initialCondition = [2;0;round(soln100.ode(1,3:6))'];
    fullSSAModel.ssaOptions.useTimeVar = true;
    fullSSAModel.ssaOptions.signalUpdateRate = 1;
    fullSSAModel.initialTime = -500;
    fullSSAModel.ssaOptions.useParallel = true;

    fullSSAModel_0p3_2StateGen = fullSSAModel.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['(TAB.dex_conc==0.3|(TAB.dex_conc==0&TAB.time==0))', ...
        '&TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685&isnan(TAB.time_tpl)']},{'replica'});
    fullSSAModel_0p3_2StateGen.parameters(13,:) = {'Dex0',0.3};

    fullSSAModel_1_2StateGen = fullSSAModel.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['(TAB.dex_conc==1|(TAB.dex_conc==0&TAB.time==0))', ...
        '&TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685&isnan(TAB.time_tpl)']},{'replica'});
    fullSSAModel_1_2StateGen.parameters(13,:) = {'Dex0',1};

    fullSSAModel_10_2StateGen = fullSSAModel.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['(TAB.dex_conc==10|(TAB.dex_conc==0&TAB.time==0))', ...
        '&TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685&isnan(TAB.time_tpl)']},{'replica'});
    fullSSAModel_10_2StateGen.parameters(13,:) = {'Dex0',10};

    fullSSAModel_100_2StateGen = fullSSAModel.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['(TAB.dex_conc==100|(TAB.dex_conc==0&TAB.time==0))', ...
        '&TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685&isnan(TAB.time_tpl)']},{'replica'});
    fullSSAModel_100_2StateGen.parameters(13,:) = {'Dex0',100};
    
    save(modelLibrary,"fullSSAModel_0p3_2StateGen","fullSSAModel_1_2StateGen", ...
        "fullSSAModel_10_2StateGen","fullSSAModel_100_2StateGen",'-append')

%% Alternate SSA Model -- No TTP Saturation
    altSSAModel_NoSaturation_100 = fullSSAModel_100_2StateGen;
    altSSAModel_NoSaturation_100.propensityFunctions{10} = ...
        'degCyt0*rCyt + (degCyt1-degCyt0)*ITTP*rCyt';
    % if regenerate
    %     altSSAModel_NoSaturation_100 = altSSAModel_NoSaturation_100.formPropensitiesGeneral('altSSAModel_NoSaturation_100');
    % end
    save(modelLibrary,"altSSAModel_NoSaturation_100",'-append')

%% Alternate SSA Model -- No TTP Time Variation
    altSSAModel_NoTimeVariation_100 = fullSSAModel_100_2StateGen;
    altSSAModel_NoTimeVariation_100.inputExpressions{2,2} = '1 + TTP1';
    % if regenerate
    %     altSSAModel_NoTimeVariation_100 = altSSAModel_NoTimeVariation_100.formPropensitiesGeneral('altSSAModel_NoTimeVariation_100');
    % end
    save(modelLibrary,"altSSAModel_NoTimeVariation_100",'-append')


%% Tryptolide
    ModelTPl = fullSSAModel_100_2StateGen;
    ModelTPl.dataSet = [];

    tptlTime = 0;
    ModelTPl_0min = ModelTPl.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['((TAB.dex_conc==100|(TAB.dex_conc==0&TAB.time==0))&isnan(TAB.time_tpl)&(TAB.time<=',num2str(tptlTime),')|', ...      %Dex=100 or iniital time and before TPL
        '(TAB.dex_conc==0&TAB.time_tpl==0&',num2str(tptlTime),'==0)&TAB.time>=TAB.time_tpl|', ...        %TPL given at time 0
        '(TAB.dex_conc==100&TAB.time_tpl==',num2str(tptlTime),'))&', ...                                 %TPL given at later time
        'TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685']},{'replica'});
    ModelTPl_0min.parameters(17,:) = {'tptlTime',0};
    
    tptlTime = 20;
    ModelTPl_20min = ModelTPl.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['((TAB.dex_conc==100|(TAB.dex_conc==0&TAB.time==0))&isnan(TAB.time_tpl)&(TAB.time<=',num2str(tptlTime),')|', ...      %Dex=100 or iniital time and before TPL
        '(TAB.dex_conc==0&TAB.time_tpl==0&',num2str(tptlTime),'==0)&TAB.time>=TAB.time_tpl|', ...        %TPL given at time 0
        '(TAB.dex_conc==100&TAB.time_tpl==',num2str(tptlTime),'))&', ...                                 %TPL given at later time
        'TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685']},{'replica'});
    ModelTPl_20min.parameters(17,:) = {'tptlTime',20};
    
    tptlTime = 75;
    ModelTPl_75min = ModelTPl.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['((TAB.dex_conc==100|(TAB.dex_conc==0&TAB.time==0))&isnan(TAB.time_tpl)&(TAB.time<=',num2str(tptlTime),')|', ...      %Dex=100 or iniital time and before TPL
        '(TAB.dex_conc==0&TAB.time_tpl==0&',num2str(tptlTime),'==0)&TAB.time>=TAB.time_tpl|', ...        %TPL given at time 0
        '(TAB.dex_conc==100&TAB.time_tpl==',num2str(tptlTime),'))&', ...                                 %TPL given at later time
        'TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685']},{'replica'});
    ModelTPl_75min.parameters(17,:) = {'tptlTime',75};
    
    tptlTime = 150;
    ModelTPl_150min = ModelTPl.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['((TAB.dex_conc==100|(TAB.dex_conc==0&TAB.time==0))&isnan(TAB.time_tpl)&(TAB.time<=',num2str(tptlTime),')|', ...      %Dex=100 or iniital time and before TPL
        '(TAB.dex_conc==0&TAB.time_tpl==0&',num2str(tptlTime),'==0)&TAB.time>=TAB.time_tpl|', ...        %TPL given at time 0
        '(TAB.dex_conc==100&TAB.time_tpl==',num2str(tptlTime),'))&', ...                                 %TPL given at later time
        'TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685']},{'replica'});
    ModelTPl_150min.parameters(17,:) = {'tptlTime',150};

    tptlTime = 180;
    ModelTPl_180min = ModelTPl.loadData(dataFileDusp1,...
        {'rna','num_nuc_noTS'; ...
        'rCyt','num_cyto_spots'},...
        {[],[],['((TAB.dex_conc==100|(TAB.dex_conc==0&TAB.time==0))&isnan(TAB.time_tpl)&(TAB.time<=',num2str(tptlTime),')|', ...      %Dex=100 or iniital time and before TPL
        '(TAB.dex_conc==0&TAB.time_tpl==0&',num2str(tptlTime),'==0)&TAB.time>=TAB.time_tpl|', ...        %TPL given at time 0
        '(TAB.dex_conc==100&TAB.time_tpl==',num2str(tptlTime),'))&', ...                                 %TPL given at later time
        'TAB.cyto_area_px>=12593&TAB.cyto_area_px<=17685']},{'replica'});
    ModelTPl_180min.parameters(17,:) = {'tptlTime',180};

    save(modelLibrary,"ModelTPl_0min","ModelTPl_20min",...
        "ModelTPl_75min","ModelTPl_150min","ModelTPl_180min",'-append')

    %%
    GR_DUSP1_TTP_Model = fullSSAModel_100_2StateGen;

    % Add Species
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addSpecies('TTP_offGene',2);
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addSpecies('TTP_onGene',2);
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addSpecies('TTP_rna',0);
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addSpecies('TTP_rCyt',0);
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addSpecies('p_TTP',0);
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addSpecies('rCyt_complex',0);
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addSpecies('TTP_rCyt_complex',0);

    % Add Reactions
    % TTP activation
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','(kon_0+kon_1_TTP*nucGR)*TTP_offGene',...
        'stoichiometry',{{'TTP_offGene',-1;'TTP_onGene',1}},...
        'parameters',{{'kon_1_TTP',1}}));
    % TTP deactivation
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','koff_TTP*TTP_onGene' ,...
        'stoichiometry',{{'TTP_offGene',1;'TTP_onGene',-1}},...
        'parameters',{{'koff_TTP',1}}));
    % TTP transcription
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','kr_on_TTP*TTP_onGene*Itrpt'  ,...
        'stoichiometry',{{'TTP_rna',1}},...
        'parameters',{{'kr_on_TTP',1}}));
    % TTP transport
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','knuc2cyt_TTP*TTP_rna'  ,...
        'stoichiometry',{{'TTP_rna',-1;'TTP_rCyt',1}},...
        'parameters',{{'knuc2cyt_TTP',1}}));
    % TTP translation
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','ktranslate*TTP_rCyt'  ,...
        'stoichiometry',{{'p_TTP',1}},...
        'parameters',{{'ktranslate',1}}));
    % TTP protein degradation
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','degProt*p_TTP'  ,...
        'stoichiometry',{{'p_TTP',-1}},...
        'parameters',{{'degProt',1}}));
    
    % TTP protein - TTP RNA binding
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','kbind*TTP_rCyt*p_TTP^TTP_eta'  ,...
        'stoichiometry',{{'TTP_rCyt',-1;'p_TTP',-1;'TTP_rCyt_complex',1}},...
        'parameters',{{'kbind',1;'TTP_eta',5}}));
    % TTP protein - DUSP1 RNA binding
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','kbind*rCyt*p_TTP^TTP_eta'  ,...
        'stoichiometry',{{'rCyt',-1;'p_TTP',-1;'rCyt_complex',1}},...
        'parameters',{{'kbind',1;'TTP_eta',5}}));
    
    % TTP protein - DUSP1 RNA binding
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','kbind*rCyt*p_TTP'  ,...
        'stoichiometry',{{'rCyt',-1;'p_TTP',-1;'rCyt_complex',1}},...
        'parameters',{{'kbind',1}}));
    
    % TTP protein - TTP RNA unbinding
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','unbind*TTP_rCyt_complex'  ,...
        'stoichiometry',{{'TTP_rCyt',1;'p_TTP',1;'TTP_rCyt_complex',-1}},...
        'parameters',{{'unbind',1}}));
    % TTP protein - DUSP1 RNA unbinding
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','unbind*rCyt_complex'  ,...
        'stoichiometry',{{'rCyt',1;'p_TTP',1;'rCyt_complex',-1}},...
        'parameters',{{'unbind',1}}));
    
    % TTP protein - DUSP1 RNA complex degradation
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','degCyt1*rCyt_complex'  ,...
        'stoichiometry',{{'rCyt_complex',-1,'p_TTP',1}},...        % 'stoichiometry',{{'rCyt_complex',-1}},...
        'parameters',[]));
    % TTP protein - TTP RNA complex degradation
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','degCyt1*TTP_rCyt_complex'  ,...
        'stoichiometry',{{'TTP_rCyt_complex',-1}},...
        'parameters',[]));
    % DUSP1 RNA Cyt degradation
    GR_DUSP1_TTP_Model.propensityFunctions{10} = 'degCyt0*rCyt';
    % TTP RNA Cyt degradation
    GR_DUSP1_TTP_Model = GR_DUSP1_TTP_Model.addReaction(struct(...
        'propensity','degCyt0_TTP*TTP_rCyt'  ,...
        'stoichiometry',{{'TTP_rCyt',-1}},...
        'parameters',{{'degCyt0_TTP',1}}));

    % save(modelLibrary,"GR_DUSP1_TTP_Model",'-append')

    %%
    % load(modelLibrary,"GR_DUSP1_TTP_Model");
    GR_DUSP1_TTP_Model_2 = GR_DUSP1_TTP_Model;
    
    % Fix Rxn 24 so TTP protein remains after complex decay.
    GR_DUSP1_TTP_Model_2.stoichiometry([10,11],24) = [-1;1];

    GR_DUSP1_TTP_Model_2 = GR_DUSP1_TTP_Model_2.removeReaction(19);
    GR_DUSP1_TTP_Model_2.propensityFilePrefix = 'Extended_GR_DUSP1';
    save(modelLibrary,"GR_DUSP1_TTP_Model_2",'-append')

    %%
    % load(modelLibrary,"GR_DUSP1_TTP_Model_2");
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_Model_2;
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addSpecies('P38u',0);
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addSpecies('P38p',0);
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addSpecies('MKP1',0);
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addSpecies('P38TTP',0);
    % 
    % % MKP1 translation
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','kMPK1*(rCyt+rCyt_complex)'  ,...
    %     'stoichiometry',{{'MPK1',1}},...
    %     'parameters',{{'kMPK1',1}}));
    % % MKP1 degradation
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','gMPK1*MPK1'  ,...
    %     'stoichiometry',{{'MPK1',-1}},...
    %     'parameters',{{'gMPK1',1}}));
    % % P38u production
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','kP38'  ,...
    %     'stoichiometry',{{'P38u',1}},...
    %     'parameters',{{'kP38',1}}));
    % % P38u degradation
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','gP38*P38u'  ,...
    %     'stoichiometry',{{'P38u',-1}},...
    %     'parameters',{{'gP38',1}}));
    % % P38p degradation
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','gP38*P38p'  ,...
    %     'stoichiometry',{{'P38p',-1}},...
    %     'parameters',[]));
    % % P38p phosphorylation
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','pP38*P38u'  ,...
    %     'stoichiometry',{{'P38u',-1;'P38p',1}},...
    %     'parameters',{{'pP38',1}}));
    % % P38p dephosphorylation (modulated by MKP1)
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','dP38*P38p*MKP1'  ,...
    %     'stoichiometry',{{'P38p',-1;'P38u',1}},...
    %     'parameters',{{'dP38',1}}));
    % % TTP-P38 sequestration
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','sequest*P38p*p_TTP'  ,...
    %     'stoichiometry',{{'P38p',-1;'P38TTP',1;'p_TTP',-1}},...
    %     'parameters',{{'sequest',1}}));
    % % TTP-P38 release
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','release*P38TTP'  ,...
    %     'stoichiometry',{{'P38p',1;'P38TTP',-1;'p_TTP',1}},...
    %     'parameters',{{'release',1}}));
    % % TTP-P38 degradation
    % GR_DUSP1_TTP_P38_Model_2 = GR_DUSP1_TTP_P38_Model_2.addReaction(struct(...
    %     'propensity','gP38*P38TTP'  ,...
    %     'stoichiometry',{{'P38TTP',-1; 'P38p',1}},...
    %     'parameters',[]));    
    % 
    % save(modelLibrary,"GR_DUSP1_TTP_P38_Model_2",'-append')

     %%
    % GR_DUSP1_TTP_P38_Model = fullSSAModel_100_2StateGen;
    % 
    % % Add Species
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('TTP_offGene',2);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('TTP_onGene',2);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('TTP_rna',0);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('TTP_rCyt',0);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('p_TTP',0);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('rCyt_complex',0);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('TTP_rCyt_complex',0);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('P38u',0);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('P38p',0);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('MKP1',0);
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addSpecies('P38TTP',0);
    % 
    % % Add Reactions
    % % TTP activation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','(kon_0+kon_1_TTP*nucGR)*TTP_offGene',...
    %     'stoichiometry',{{'TTP_offGene',-1;'TTP_onGene',1}},...
    %     'parameters',{{'kon_1_TTP',1}}));
    % % TTP deactivation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','koff_TTP*TTP_onGene' ,...
    %     'stoichiometry',{{'TTP_offGene',1;'TTP_onGene',-1}},...
    %     'parameters',{{'koff_TTP',1}}));
    % % TTP transcription
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','kr_on_TTP*TTP_onGene*Itrpt'  ,...
    %     'stoichiometry',{{'TTP_rna',1}},...
    %     'parameters',{{'kr_on_TTP',1}}));
    % % TTP transport
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','knuc2cyt_TTP*TTP_rna'  ,...
    %     'stoichiometry',{{'TTP_rna',-1;'TTP_rCyt',1}},...
    %     'parameters',{{'knuc2cyt_TTP',1}}));
    % % TTP translation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','ktranslate*TTP_rCyt'  ,...
    %     'stoichiometry',{{'p_TTP',1}},...
    %     'parameters',{{'ktranslate',1}}));
    % % TTP protein degradation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','degProt*p_TTP'  ,...
    %     'stoichiometry',{{'p_TTP',-1}},...
    %     'parameters',{{'degProt',1}}));
    % % TTP protein - TTP RNA binding
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','kbind*TTP_rCyt*p_TTP^TTP_eta'  ,...
    %     'stoichiometry',{{'TTP_rCyt',-1;'p_TTP',-1;'TTP_rCyt_complex',1}},...
    %     'parameters',{{'kbind',1;'TTP_eta',5}}));
    % % TTP protein - DUSP1 RNA binding
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','kbind*rCyt*p_TTP^TTP_eta'  ,...
    %     'stoichiometry',{{'rCyt',-1;'p_TTP',-1;'rCyt_complex',1}},...
    %     'parameters',{{'kbind',1;'TTP_eta',5}}));
    % % TTP protein - DUSP1 RNA binding
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','kbind*rCyt*p_TTP'  ,...
    %     'stoichiometry',{{'rCyt',-1;'p_TTP',-1;'rCyt_complex',1}},...
    %     'parameters',{{'kbind',1}}));
    % % TTP protein - TTP RNA unbinding
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','unbind*TTP_rCyt_complex'  ,...
    %     'stoichiometry',{{'TTP_rCyt',1;'p_TTP',1;'TTP_rCyt_complex',-1}},...
    %     'parameters',{{'unbind',1}}));
    % % TTP protein - DUSP1 RNA unbinding
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','unbind*rCyt_complex'  ,...
    %     'stoichiometry',{{'rCyt',1;'p_TTP',1;'rCyt_complex',-1}},...
    %     'parameters',{{'unbind',1}}));
    % % TTP protein - DUSP1 RNA complex degradation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','degCyt1*rCyt_complex'  ,...
    %     'stoichiometry',{{'rCyt_complex',-1}},...
    %     'parameters',[]));
    % % TTP protein - TTP RNA complex degradation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','degCyt1*TTP_rCyt_complex'  ,...
    %     'stoichiometry',{{'TTP_rCyt_complex',-1}},...
    %     'parameters',[]));
    % % DUSP1 RNA Cyt degradation
    % GR_DUSP1_TTP_P38_Model.propensityFunctions{10} = 'degCyt0*rCyt';
    % % TTP RNA Cyt degradation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','degCyt0_TTP*TTP_rCyt'  ,...
    %     'stoichiometry',{{'TTP_rCyt',-1}},...
    %     'parameters',{{'degCyt0_TTP',1}}));
    % 
    % % MKP1 translation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','kMPK1*(rCyt+rCyt_complex)'  ,...
    %     'stoichiometry',{{'MPK1',1}},...
    %     'parameters',{{'kMPK1',1}}));
    % % MKP1 degradation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','gMPK1*MPK1'  ,...
    %     'stoichiometry',{{'MPK1',-1}},...
    %     'parameters',{{'gMPK1',1}}));
    % % P38u production
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','kP38'  ,...
    %     'stoichiometry',{{'P38u',1}},...
    %     'parameters',{{'kP38',1}}));
    % % P38u degradation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','gP38*P38u'  ,...
    %     'stoichiometry',{{'P38u',-1}},...
    %     'parameters',{{'gP38',1}}));
    % % P38p degradation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','gP38*P38p'  ,...
    %     'stoichiometry',{{'P38p',-1}},...
    %     'parameters',[]));
    % % P38p phosphorylation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','pP38*P38u'  ,...
    %     'stoichiometry',{{'P38u',-1;'P38p',1}},...
    %     'parameters',{{'pP38',1}}));
    % % P38p dephosphorylation (modulated by MKP1)
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','dP38*P38p*MKP1'  ,...
    %     'stoichiometry',{{'P38p',-1;'P38u',1}},...
    %     'parameters',{{'dP38',1}}));
    % % TTP-P38 sequestration
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','sequest*P38p*p_TTP'  ,...
    %     'stoichiometry',{{'P38p',-1;'P38TTP',1;'p_TTP',-1}},...
    %     'parameters',{{'sequest',1}}));
    % % TTP-P38 release
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','release*P38TTP'  ,...
    %     'stoichiometry',{{'P38p',1;'P38TTP',-1;'p_TTP',1}},...
    %     'parameters',{{'release',1}}));
    % % TTP-P38 degradation
    % GR_DUSP1_TTP_P38_Model = GR_DUSP1_TTP_P38_Model.addReaction(struct(...
    %     'propensity','gP38*P38TTP'  ,...
    %     'stoichiometry',{{'P38TTP',-1}},...
    %     'parameters',[]));
    % save(modelLibrary,"GR_DUSP1_TTP_P38_Model",'-append')

    
 %%
   
 
end
Models = load(modelLibrary,modelName,'log10PriorMean','log10PriorStd');
Model = Models.(modelName);
log10PriorMean = Models.log10PriorMean;
log10PriorStd = Models.log10PriorStd;
